### ISSUE TITLE
UI interactions allowed while logged out

### ISSUE THREAD

**Issue by thejonas** [overview/overview-server#123]
If the user is logged out while they have an page open to the document set list or a specific document set, they can still perform some operations without being prompted to login:
1. Delete - Confirmation dialog pops up before login prompt
2. collapse nodes in tree
3. Add and Delete tags (doesn't change database)
4. List documents under a node

**Comment by adamhooper** [comment]
Nowadays, w ask the user to re-log-in when a request fails.
