### ISSUE TITLE
Password reset allows login without confirmation

### ISSUE THREAD

**Issue by thejonas** [overview/overview-server#219]
1. Register a new account
2. Before clicking on the confirmation link sent in email, click on Reset Password on login page.
3. Enter email of new account
4. Click on password reset link sent in email
5. Enter a new password'

Expected: Same as if trying to login before confirming
Actual: User is logged in.

**Comment by adamhooper** [comment]
Closing. Nobody has asked for this to change. This "bug" may benefit some users, and it's not clear that it causes any harm.
