### ISSUE TITLE
Silverlight installation/upgrade requires reloading of page

### ISSUE THREAD

**Issue by thejonas** [overview/overview-server#235]
When first trying upload from IE9, I was prompted to upgrade Silverlight. After the process was completed, the upload dialog window was still visible, but there was no "choose file" button. 
A page reload was needed to get the upload working.

A nicer user experience might be to generate a prompt as soon as the "Upload document set" button is  hit, saying "You need to install/upload silverlight in order to upload files" along with other reassuring noises. Windows makes installing software scary sounding ("this may damage your computer"), so some users may be reluctant to proceed (especially if they have no idea what silverlight is).

**Comment by adamhooper** [comment]
We don't use Silverlight any more. Solved!
