### ISSUE TITLE
Can't delete users with failed uploads

### ISSUE THREAD

**Issue by thejonas** [overview/overview-server#243]
Users with failed or cancelled uploads still have entries in the Upload table even after deleting all document sets, and can't be deleted.
We could work around this issue if we had a "manage downloads" page as discussed in #238, but maybe Delete user should just automatically delete all associated tables (and log entries)?

**Comment by adamhooper** [comment]
Fixed in ac098a87c908023e56f2bda8fb3416c452a346d9
