### ISSUE TITLE
Importing the same document set leads to different clustering

### ISSUE THREAD

**Issue by thejonas** [overview/overview-server#287]
- Import a DocumentSet multiple times (CsvImport or DocumentCloud)
Result: The resulting clustering differs each time.

The clustering algorithm selects documents from a Map where the Document id is the key. Different Document Ids lead to a different order , resulting in a different clustering.

Solution: Ensure that everytime a document set is imported, each document receives the same id. This id, composed with the documentSetId should then be used as the Document Id in the database (rather than an autogenerated id).

For CsvImport: The Id is based on the order in which the Document is extracted from the CSV file (essentially, the row index)

For DocumentCloud: Use the 32bit id encoded in a DocumentCloudId

**Comment by adamhooper** [comment]
Nowadays, every time a document set is imported, each document receives the same ID. (Exception: file upload.)
