### ISSUE TITLE
Server opens more than 10 database connection if user has multiple failed jobs

### ISSUE THREAD

**Issue by thejonas** [overview/overview-server#304]
1. Import a CSV file that will fail with a worker error 5 - 10 times
   (eg. upload a UTF-16 file but specify the encoding as UTF-8)
2. Some actions I took - Not sure which, if any, cause the problem:
* Open multiple tabs showing the document set list
* Import some successful jobs.
* Let the browser sit with the tab open for ~30 minutes.

Observe the number of database connections. The server will (maybe) have more than 10 connections open, even though the connection pool size is 10.

(only tried on Heroku)

**Comment by adamhooper** [comment]
I assume we fixed this years ago.
