### ISSUE TITLE
After deleting a job on second page, 1st page is loaded

### ISSUE THREAD

**Issue by thejonas** [overview/overview-server#326]
1. Import document sets until they are split over 2+ pages
2. Navigate to the 2nd page
3. Delete a job

Expected: browser stays on page 2 (if there sufficient document sets)
Actual: redirected to first page

**Comment by adamhooper** [comment]
Yay for reopening a minor-nit bug and keeping it open for two years. closing.

I imagine sometime soon the cancel button won't do a page refresh anyway.
