### ISSUE TITLE
Clustering spends 1/3 of its time waiting for DB to check for cancellation

### ISSUE THREAD

**Issue by jstray** [overview/overview-server#369]
Timings on my dev machine, importing drones set:

Current version:
18:02:13.567 INFO  WORKER - Clustered documents, time: 31.445 seconds
18:03:13.333 INFO  WORKER - Clustered documents, time: 28.492 seconds
18:06:19.625 INFO  WORKER - Clustered documents, time: 28.352 seconds
18:08:20.393 INFO  WORKER - Clustered documents, time: 30.624 seconds

With cancellation check (j.state == CANCELLED) commented out:
18:13:46.790 INFO  WORKER - Clustered documents, time: 25.431 seconds
18:14:44.100 INFO  WORKER - Clustered documents, time: 22.024 seconds
18:15:52.829 INFO  WORKER - Clustered documents, time: 21.495 seconds
18:18:19.440 INFO  WORKER - Clustered documents, time: 21.642 seconds

To confirm, I'm also seeing this in VisualVM where we spend as much time in org.postgresql.core.VisibleBufferedInputStream.readMore() as we do in org.overviewproject.clustering.KMeansDocumentOps.distance()

We should be reading the cancel state on another thread while the clustering is happening. Could be done using actors to wrap DB requests, but not really necessary. See e.g. http://stackoverflow.com/questions/4087696/is-asynchronous-jdbc-call-possible and  http://www.gamlor.info/wordpress/2012/05/async-sql-and-akka/

**Comment by adamhooper** [comment]
We have other issues on Pivotal that target this problem. And the polling doesn't eat up 1/3 of the time any more.
