### ISSUE TITLE
See if we can support HTTP urls

### ISSUE THREAD

**Issue by jstray** [overview/overview-server#414]
Being able to display http urls is essential to direct CSV import form social media listening tools, #413. With appropriate iframe security settings, the risk seems to be that a site will trick the user into giving up credentials, possibly a fake site using MITM attack. Perhaps this is an acceptable risk with the right sort of user education, maybe a warning on import about this.

**Comment by adamhooper** [comment]
We haven't supported HTTP for years, and this hasn't come up once. I'm cleaning this up on GitHub; if it's an issue again, we should add it to the Pivotal Icebox.
