### ISSUE TITLE
Set as example document set checkbox does not update properly

### ISSUE THREAD

**Issue by thejonas** [overview/overview-server#434]
1. Login as admin
2. Click Share button
3. Check Set as Example Document set checkbox
4. Close dialog box
5. Click share button again

Expected: Checkbox is checked
Actual: Checkbox is not checked. Reload fixes the problem.

**Comment by adamhooper** [comment]
Redone a couple of weeks ago. Now the checkbox is in an iframe, so we're guaranteed a reload when we open the dialog again.
