### ISSUE TITLE
Show all tags on a node simultaneously

### ISSUE THREAD

**Issue by jstray** [overview/overview-server#469]
Right now we draw only the most recently selected tag, which users find confusing. I've resisted showing all tags because they can overlap in arbitrary ways, and add up to more than 100%. Now I don't care. Here's my new idea:

- the "tag stripe" we have now will be multi-colored, ordered in the same way as the tag list. It will show, proportionally, how many documents have each tag.
- it will be as wide as the number of documents which have any tag. 

So if all documents are tagged with two tags A and B, we will see 50% A and 50% B. If half are tagged with A and the other half are tagged with B, we will see the same. If the same half are tagged with both A and B, and the other half has no tags, we will see 25% A, 25% B, and the rest blank.

**Comment by adamhooper** [comment]
If we really need this, it should be on our Pivotal icebox.

In the meantime, b472e32f1c036697c073837d8e2295d0b7c448a6 shows all tag counts for the currently-selected document list.
