### ISSUE TITLE
Create guest accounts so users can try Overview without registering

### ISSUE THREAD

**Issue by jstray** [overview/overview-server#470]
Here's the basic shape I imagine:

- "try it now" button on main page creates a session-based guest account, an actual user in the DB
- when user tries to leave page, we warn them that they will lose their work -- "register now to save your work"
- "log out" link for guest user says "register to save" instead, and highlighted.
- Flash on /documentsets, saying "register to save your work" and providing link to a registration page
- when guest user registers, we upgrade their account to a normal account
- delete a guest account that has gone 24 hours with no interaction

**Comment by adamhooper** [comment]
We haven't talked about a "guest account" for years. I think we're more likely to opt for public-access document sets instead. And we track that on Pivotal.
