### ISSUE TITLE
Create document snippets when building tree, and store to database

### ISSUE THREAD

**Issue by jstray** [overview/overview-server#471]
Not entirely clear how to do this. Possibilities

- key sentence detection, perhaps Luhn's algorithm? https://text-analysis.googlecode.com/files/luhn58.pdf
- show sentence(s) containing most highly tf-idf ranked word(s)
- take the first X characters/words of doc
- take first X characters of document "content", that is, try to skip headers etc.

**Comment by adamhooper** [comment]
Nothing wrong with this as a brainstorm idea, but I'm clearing up GitHub issues and this one seems worth dismissing for now.
