### ISSUE TITLE
Worker can hang

### ISSUE THREAD

**Issue by thejonas** [overview/overview-server#510]
I discovered the worker not processing any jobs on production. It looks like had been stuck since Friday. 

ps showed:
0 S overview 10848 10847  0  80   0 - 456962 futex_ May06 ?       00:43:51 /usr/bin/java -cp /opt/overview/m ...

The job was a dc import of a 1 page document, being split into multiple files.

After restarting the worker, the job started processing and completed normally.

**Comment by adamhooper** [comment]
I'll assume this stopped 30 months ago.
