### ISSUE TITLE
Reload is necessary to make search work again if connection to message queue breaks and is restored

### ISSUE THREAD

**Issue by thejonas** [overview/overview-server#525]
1. Start the system, with no message queue running
2. Start a search
3. Start the message queue
4. Start a second search on the same document set

Expected: The second search succeeds. The first search tag disappears, possibly.
Actual: The second search is never submitted and never completes.

**Comment by adamhooper** [comment]
This particular bug is not reproducible now, because searching doesn't use the message queue. There may be a broader problem; but if so, we should put it on Pivotal. I'm tidying up GitHub issues here :).
