### ISSUE TITLE
View Document in Fullscreen does not open document to specific page

### ISSUE THREAD

**Issue by thejonas** [overview/overview-server#558]
- Import a document set from documentcloud, splitting pages
- Open the document set
- Select a document and click the "View Document in Full Screen"

Expected: Viewer opens the document at the correct page
Actual: Viewer opens the document at page 1

We probably can't fix this one either, but along with #556 indicates that the DC viewer in an iframe isn't serving us as well as we might want it to.

**Comment by adamhooper** [comment]
Aaand it's fixed (ages ago)
