### ISSUE TITLE
Develop a Docker deployment

### ISSUE THREAD

**Issue by znmeb** [overview/overview-server#621]
Opening an issue to track this: plan

1. Get an Overview development environment running. I'm using Fedora 21 64-bit but it should work anywhere the development environment does.
2. Get a Docker development environment up. Again, I'm on Fedora 21 64-bit but this could be done anywhere.
3. Create a Docker image. I'm recommending Ubuntu 14.04 LTS (Trusty Tahr) 64-bit as the base. Fedora 21 is midway between alpha and beta and there's no official Docker image for stable versions of Fedora before that. Fedora 21 release is after the Nov 12 hackathon. ;-)
4. Layer PostgreSQL and OpenJDK onto the Docker image. I'm pretty sure there's an existing PostgreSQL / Ubuntu 14.04 Docker image but I don't know about OpenJDK.
5. Do a release build from the Overview development server.
6. Install and test the release in the Docker image. Fix all the bugs going back to step 1 if necessary.
7. Test on Windows 8.1 Boot2Docker and MacOS X Boot2Docker. You'll probably need to test both Mavericks and Yosemite given the Nov 12 deadline and the noise I'm hearing about Yosemite breaking command line stuff.

**Comment by adamhooper** [comment]
We go from zero to complete in https://github.com/overview/overview-local
