### ISSUE TITLE
Intro video on Vimeo requires Flash plugin

### ISSUE THREAD

**Issue by znmeb** [overview/overview-server#622]
When I build the Overview developer environment it comes up at the login page pointing to a Vimeo intro video. The last time I tried it on a Fedora 21 beta it told me I couldn't play the video. Installing the browser Flash plugin fixed it.

On a freshly installed Linux system the Flash player won't be there- you have to accept an Adobe license to get it and support is spotty. And some distros, like Fedora, don't even ship a package to go out and get the Flash plugin.

So I'd recommend converting the video to something that's supported on Linux without a plugin requirement. I haven't kept track of where the browsers are these days - I'm pretty sure you'll need a format that runs on an iPad, but I think Firefox and Chromium will both play that format.

**Comment by adamhooper** [comment]
Vimeo no longer uses Flash.
