### ISSUE TITLE
Miscellaneous requests for the Docker deployment

### ISSUE THREAD

**Issue by znmeb** [overview/overview-server#624]
1. Is there some way we can minimize the debug output to the console? I can run the Docker container in the background, which will eliminate that problem, but it's hard to tell when the server is ready to accept connections that way, and it's also hard to tell if something died. You have to explicitly ask for a log file. 

2. Is there some way we can control how much Java memory gets allocated on the "./run" command? We can push the guest Linux machine where the Docker containers run up to half the host RAM, but if Java can't see that, there's no point.

**Comment by adamhooper** [comment]
We address this stuff in our latest Docker configs.
