### ISSUE TITLE
Docker Hub flakiness

### ISSUE THREAD

**Issue by znmeb** [overview/overview-server#634]
I've reached the breaking point with Docker Hub and am migrating my projects to Quay.io. Docker Hub's automatic build process is currently unreliable. It suffers from network connectivity issues and mysterious failures that sometimes persist for several tries before finally completing a build; the same build works every time on my workstation. 

On top of that, I had to break an integrated build into three pieces just to get it to build at all on Docker Hub. On Quay.io, the whole thing builds *and* it caches intermediate steps just like a 'docker build' does on a workstation.

I'm still getting emails from Docker Hub occasionally when one of these glitches hits the Overview build. I'm ignoring them and have no plans to drop my Docker Hub account. If you want help migrating to Quay.io, let me know.

**Comment by yifuguo** [comment]
is there an up to date version of overview-server docker image?

**Comment by adamhooper** [comment]
This is a bug we can't fix. Closing.
