### ISSUE TITLE
Dependency resolution fails on updated Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by borpglass** [overview/overview-server#635]
This is probably a low-priority issue, since it appears to only play a role on one specific machine. That said, a fix may help a few users. 

PostgreSQL, Java 8 SDK, git and LibreOffice are all present on our Ubuntu 14.04 LTS box. It looks like the   /.dev   command listed at   https://github.com/overview/overview-server/wiki/Setting-up-a-development-Environment   is supposed to resolve any remaining dependencies, but it is still having some trouble. Perhaps a friendlier error message is possible? (In that case, I could then manually fix whatever is missing). Here is the last bit of console output before the script stalls: 

[info] [overview-server] Running '/usr/lib/jvm/java-8-openjdk-i386/jre/bin/java' '-Duser.timezone=UTC' '-Dpidfile.enabled=false' '-Dsbt.jse.engineType=Trireme' '-Doverview.is32BitJava=true' '-jar' '/home/data-desk-ubuntu/overview-server/runner/target/scala-2.11/classes/sbt-launch.jar' 'run'
[info] [redis] Running './deps/redis/dev.sh'
[info] [worker] Running DATABASE_NAME='overview-dev' DATABASE_PORT='9010' DATABASE_SSL_FACTORY='org.postgresql.ssl.NonValidatingFactory' '/usr/lib/jvm/java-8-openjdk-i386/jre/bin/java' '-Xmx1300m' '-Doverview.is32BitJava=true' '-Doverview.is32BitJava=true' 'JobHandler'
[info] [redis] cd src && make redis-server
[error] ERROR - [worker] Error: Could not find or load main class JobHandler
[info] Killing processes...
[info] [worker] Sending kill signal
[info] [search-index] Sending kill signal
[info] [documentset-worker] Sending kill signal
[info] [overview-server] Sending kill signal
[info] [message-broker] Sending kill signal
[info] [redis] Sending kill signal
[info] [worker] Exited with status code 1.
[info] [search-index] Exited with status code 143.
[info] [documentset-worker] Exited with status code 143.
[info] [overview-server] Exited with status code 143.
[info] [message-broker] Exited with status code 143.
[info] [redis] Exited with status code 143.
[info] All processes exited. (First exit status code was 1. Shutting down.
java.lang.RuntimeException: Nonzero exit code returned from runner: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last runner/compile:run for the full output.
[error] (runner/compile:run) Nonzero exit code returned from runner: 1
[error] Total time: 26 s, completed Aug 6, 2015 9:52:00 AM

**Comment by thejonas** [comment]
This looks like an issue we see occasionally with the Scala build system.
What happens if you run ./dev again?
You could also try to first auto/clean-fully.sh and then rerun ./dev

**Comment by borpglass** [comment]
Hmm ... no luck. It's possible that one of the other few programs we had installed on here had messed with an assumed setting somewhere. Thankfully, this is pretty much a disposable machine. I'll try maybe doing a fresh installation of Fedora or something and running the directions associated with that distribution. Thanks for the suggestions.

**Comment by borpglass** [comment]
I have attempted a fresh Fedora imaging/install. Since that is a different OS, I have moved our difficulties with that installation into a different issue:

https://github.com/overview/overview-server/issues/637
