### ISSUE TITLE
Redis compilation fails on Fedora 22

### ISSUE THREAD

**Issue by borpglass** [overview/overview-server#637]
On a freshly-imaged Fedora 22 workstation, I have installed all dependencies per  https://github.com/overview/overview-server/wiki/Setting-up-a-development-Environment  and tried to run the  /.dev  script. 

According to those instructions, that script is supposed to resolve any remaining dependencies, but it is still having some trouble. Perhaps a friendlier error message is possible? (In that case, I could then manually fix whatever is missing). 

Re-running the script and/or running clean-fully.sh (as suggested in issue 635) does not appear to change the behavior. 

Here is the console output before the script stalls: 

$ ./dev
which: no node in (/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/datadesk/.local/bin:/home/datadesk/bin)
+ java -Xms512M -Xmx2048M -Xss1M -XX:+CMSClassUnloadingEnabled -Dsbt.jse.engineType=Trireme -jar ./runner/src/main/resources/sbt-launch.jar 'runner/run '
[info] Loading project definition from /home/datadesk/overview-server/project
[info] Set current project to overview-server (in build file:/home/datadesk/overview-server/)
[info] Updating {file:/home/datadesk/overview-server/}runner...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Compiling 16 Scala sources to /home/datadesk/overview-server/runner/target/scala-2.11/classes...
[info] Running com.overviewdocs.runner.Main 
[info] Preparing to start search-index, message-broker, overview-server, documentset-worker, redis, worker
[info] [database] Database found in /home/datadesk/overview-server/database. If you move or delete that directory, Overview will create a new database next time you run it.
[info] [database] Wrote /home/datadesk/overview-server/database/postgresql.conf
[info] [database] Wrote /home/datadesk/overview-server/database/server.crt
[info] [database] Wrote /home/datadesk/overview-server/database/server.key
[info] [database] Running '/usr/bin/postgres' '-D' '/home/datadesk/overview-server/database' '-k' '/home/datadesk/overview-server/database'
[info] [database] pid=5884 xid=0 FATAL:  F0001: lock file "postmaster.pid" already exists
[info] [database] pid=5884 xid=0 HINT:  Is another postmaster (PID 5354) running in data directory "/home/datadesk/overview-server/database"?
[info] [database] pid=5884 xid=0 LOCATION:  CreateLockFile, miscinit.c:763
[info] Running evolutions...
[info] [evolutions] Running DATABASE_NAME='overview-dev' DATABASE_PORT='9010' DATABASE_SSL_FACTORY='org.postgresql.ssl.NonValidatingFactory' '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.51-4.b16.fc22.x86_64/jre/bin/java' '-Dsbt.log.format=false' '-jar' '/home/datadesk/overview-server/runner/target/scala-2.11/classes/sbt-launch.jar' 'db-evolution-applier/run'
[info] [evolutions] [info] Loading project definition from /home/datadesk/overview-server/project
[info] [evolutions] [info] Set current project to overview-server (in build file:/home/datadesk/overview-server/)
[info] [evolutions] [info] Updating {file:/home/datadesk/overview-server/}db-evolution-applier...
[info] [evolutions] [info] Resolving jline#jline;2.12.1 ...
[info] [evolutions] [info] Done updating.
[info] [evolutions] [info] Compiling 1 Scala source to /home/datadesk/overview-server/db-evolution-applier/target/db-evolution-applier/scala-2.11/classes...
[info] [evolutions] [info] Running com.overviewdocs.db_evolution_applier.Main 
[info] [evolutions] [info] 18:12:31.092 [main] DEBUG com.zaxxer.hikari.HikariConfig - HikariCP pool HikariPool-0 configuration:
[info] [evolutions] [info] 18:12:31.142 [main] DEBUG com.zaxxer.hikari.HikariConfig - allowPoolSuspension.............false
[info] [evolutions] [info] 18:12:31.143 [main] DEBUG com.zaxxer.hikari.HikariConfig - autoCommit......................true
[info] [evolutions] [info] 18:12:31.143 [main] DEBUG com.zaxxer.hikari.HikariConfig - catalog.........................
[info] [evolutions] [info] 18:12:31.145 [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionCustomizer............com.zaxxer.hikari.AbstractHikariConfig$1@2928854b
[info] [evolutions] [info] 18:12:31.145 [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionCustomizerClassName...
[info] [evolutions] [info] 18:12:31.145 [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionInitSql...............
[info] [evolutions] [info] 18:12:31.145 [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionTestQuery.............
[info] [evolutions] [info] 18:12:31.146 [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionTimeout...............30000
[info] [evolutions] [info] 18:12:31.146 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSource......................
[info] [evolutions] [info] 18:12:31.146 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceClassName.............org.postgresql.ds.PGSimpleDataSource
[info] [evolutions] [info] 18:12:31.147 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceJNDI..................
[info] [evolutions] [info] 18:12:31.147 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceProperties............{user=overview, password=<masked>, tcpKeepAlive=true, portNumber=9010, databaseName=overview-dev, sslfactory=org.postgresql.ssl.NonValidatingFactory, serverName=localhost}
[info] [evolutions] [info] 18:12:31.147 [main] DEBUG com.zaxxer.hikari.HikariConfig - driverClassName.................
[info] [evolutions] [info] 18:12:31.147 [main] DEBUG com.zaxxer.hikari.HikariConfig - healthCheckProperties...........{}
[info] [evolutions] [info] 18:12:31.148 [main] DEBUG com.zaxxer.hikari.HikariConfig - healthCheckRegistry.............
[info] [evolutions] [info] 18:12:31.148 [main] DEBUG com.zaxxer.hikari.HikariConfig - idleTimeout.....................600000
[info] [evolutions] [info] 18:12:31.148 [main] DEBUG com.zaxxer.hikari.HikariConfig - initializationFailFast..........true
[info] [evolutions] [info] 18:12:31.148 [main] DEBUG com.zaxxer.hikari.HikariConfig - isolateInternalQueries..........false
[info] [evolutions] [info] 18:12:31.148 [main] DEBUG com.zaxxer.hikari.HikariConfig - jdbc4ConnectionTest.............false
[info] [evolutions] [info] 18:12:31.149 [main] DEBUG com.zaxxer.hikari.HikariConfig - jdbcUrl.........................
[info] [evolutions] [info] 18:12:31.150 [main] DEBUG com.zaxxer.hikari.HikariConfig - leakDetectionThreshold..........0
[info] [evolutions] [info] 18:12:31.150 [main] DEBUG com.zaxxer.hikari.HikariConfig - maxLifetime.....................1800000
[info] [evolutions] [info] 18:12:31.151 [main] DEBUG com.zaxxer.hikari.HikariConfig - maximumPoolSize.................2
[info] [evolutions] [info] 18:12:31.151 [main] DEBUG com.zaxxer.hikari.HikariConfig - metricRegistry..................
[info] [evolutions] [info] 18:12:31.151 [main] DEBUG com.zaxxer.hikari.HikariConfig - minimumIdle.....................2
[info] [evolutions] [info] 18:12:31.151 [main] DEBUG com.zaxxer.hikari.HikariConfig - password........................<masked>
[info] [evolutions] [info] 18:12:31.151 [main] DEBUG com.zaxxer.hikari.HikariConfig - poolName........................HikariPool-0
[info] [evolutions] [info] 18:12:31.151 [main] DEBUG com.zaxxer.hikari.HikariConfig - readOnly........................false
[info] [evolutions] [info] 18:12:31.151 [main] DEBUG com.zaxxer.hikari.HikariConfig - registerMbeans..................false
[info] [evolutions] [info] 18:12:31.151 [main] DEBUG com.zaxxer.hikari.HikariConfig - threadFactory...................
[info] [evolutions] [info] 18:12:31.151 [main] DEBUG com.zaxxer.hikari.HikariConfig - transactionIsolation............
[info] [evolutions] [info] 18:12:31.151 [main] DEBUG com.zaxxer.hikari.HikariConfig - username........................
[info] [evolutions] [info] 18:12:31.151 [main] DEBUG com.zaxxer.hikari.HikariConfig - validationTimeout...............5000
[info] [evolutions] [info] 18:12:31.153 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariCP pool HikariPool-0 is starting.
[info] [evolutions] [info] 18:12:31.278 [main] DEBUG com.zaxxer.hikari.pool.PoolUtilities - HikariPool-0 - Connection.setNetworkTimeout() not supported
[info] [evolutions] [info] 18:12:31.366 [HikariCP connection filler (pool HikariPool-0)] DEBUG com.zaxxer.hikari.pool.HikariPool - After fill pool stats HikariPool-0 (total=2, inUse=0, avail=2, waiting=0)
[info] [evolutions] [info] Database schema is fresh: there are no more evolutions to apply
[info] [evolutions] [success] Total time: 11 s, completed Aug 7, 2015 2:12:31 PM
[info] Compiling and fetching...
[info] [sbt] Running '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.51-4.b16.fc22.x86_64/jre/bin/java' '-Dsbt.log.format=false' '-Xmx2g' '-jar' '/home/datadesk/overview-server/runner/target/scala-2.11/classes/sbt-launch.jar' '; search-index/compile; show search-index/full-classpath; message-broker/compile; show message-broker/full-classpath; documentset-worker/compile; show documentset-worker/full-classpath; worker/compile; show worker/full-classpath'
[info] [sbt] [info] Loading project definition from /home/datadesk/overview-server/project
[info] [sbt] [info] Set current project to overview-server (in build file:/home/datadesk/overview-server/)
[info] [sbt] [info] Updating {file:/home/datadesk/overview-server/}search-index...
[info] [sbt] [info] Resolving jline#jline;2.12.1 ...
[info] [sbt] [info] Done updating.
[info] [sbt] [info] Compiling 1 Java source to /home/datadesk/overview-server/search-index/target/scala-2.11/classes...
[info] [sbt] java.io.IOException: Cannot run program "javac" (in directory "/home/datadesk/overview-server"): error=2, No such file or directory
[info] [sbt] 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
[info] [sbt] 	at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:349)
[info] [sbt] 	at sbt.AbstractProcessBuilder.run(ProcessImpl.scala:128)
[info] [sbt] 	at sbt.AbstractProcessBuilder$$anonfun$runBuffered$1.apply(ProcessImpl.scala:159)
[info] [sbt] 	at sbt.AbstractProcessBuilder$$anonfun$runBuffered$1.apply(ProcessImpl.scala:159)
[info] [sbt] 	at sbt.compiler.javac.JavacLogger.buffer(JavacProcessLogger.scala:31)
[info] [sbt] 	at sbt.AbstractProcessBuilder.runBuffered(ProcessImpl.scala:159)
[info] [sbt] 	at sbt.AbstractProcessBuilder.$bang(ProcessImpl.scala:156)
[info] [sbt] 	at sbt.compiler.javac.ForkedJava$$anonfun$launch$1.apply(ForkedJava.scala:24)
[info] [sbt] 	at sbt.compiler.javac.ForkedJava$$anonfun$launch$1.apply(ForkedJava.scala:17)
[info] [sbt] 	at sbt.compiler.javac.ForkedJava$$anonfun$withArgumentFile$1.apply(ForkedJava.scala:47)
[info] [sbt] 	at sbt.compiler.javac.ForkedJava$$anonfun$withArgumentFile$1.apply(ForkedJava.scala:44)
[info] [sbt] 	at sbt.IO$.withTemporaryDirectory(IO.scala:291)
[info] [sbt] 	at sbt.compiler.javac.ForkedJava$.withArgumentFile(ForkedJava.scala:44)
[info] [sbt] 	at sbt.compiler.javac.ForkedJava$.launch(ForkedJava.scala:17)
[info] [sbt] 	at sbt.compiler.javac.ForkedJavaCompiler.run(ForkedJava.scala:68)
[info] [sbt] 	at sbt.compiler.javac.JavaCompilerAdapter.compileWithReporter(JavaCompilerAdapter.scala:31)
[info] [sbt] 	at sbt.compiler.javac.AnalyzingJavaCompiler$$anonfun$compile$1.apply$mcV$sp(AnalyzingJavaCompiler.scala:65)
[info] [sbt] 	at sbt.compiler.javac.AnalyzingJavaCompiler$$anonfun$compile$1.apply(AnalyzingJavaCompiler.scala:65)
[info] [sbt] 	at sbt.compiler.javac.AnalyzingJavaCompiler$$anonfun$compile$1.apply(AnalyzingJavaCompiler.scala:65)
[info] [sbt] 	at sbt.compiler.javac.AnalyzingJavaCompiler.timed(AnalyzingJavaCompiler.scala:93)
[info] [sbt] 	at sbt.compiler.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:64)
[info] [sbt] 	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileJava$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:61)
[info] [sbt] 	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileJava$1$1.apply(MixedAnalyzingCompiler.scala:61)
[info] [sbt] 	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileJava$1$1.apply(MixedAnalyzingCompiler.scala:61)
[info] [sbt] 	at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:75)
[info] [sbt] 	at sbt.compiler.MixedAnalyzingCompiler.compileJava$1(MixedAnalyzingCompiler.scala:60)
[info] [sbt] 	at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:65)
[info] [sbt] 	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
[info] [sbt] 	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
[info] [sbt] 	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
[info] [sbt] 	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
[info] [sbt] 	at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:31)
[info] [sbt] 	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:62)
[info] [sbt] 	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:61)
[info] [sbt] 	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:89)
[info] [sbt] 	at sbt.inc.Incremental$.compile(Incremental.scala:61)
[info] [sbt] 	at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
[info] [sbt] 	at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
[info] [sbt] 	at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
[info] [sbt] 	at sbt.Compiler$.compile(Compiler.scala:128)
[info] [sbt] 	at sbt.Compiler$.compile(Compiler.scala:114)
[info] [sbt] 	at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:814)
[info] [sbt] 	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:805)
[info] [sbt] 	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:803)
[info] [sbt] 	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[info] [sbt] 	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
[info] [sbt] 	at sbt.std.Transform$$anon$4.work(System.scala:63)
[info] [sbt] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
[info] [sbt] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
[info] [sbt] 	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[info] [sbt] 	at sbt.Execute.work(Execute.scala:235)
[info] [sbt] 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
[info] [sbt] 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
[info] [sbt] 	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[info] [sbt] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[info] [sbt] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] [sbt] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info] [sbt] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] [sbt] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info] [sbt] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info] [sbt] 	at java.lang.Thread.run(Thread.java:745)
[info] [sbt] Caused by: java.io.IOException: error=2, No such file or directory
[info] [sbt] 	at java.lang.UNIXProcess.forkAndExec(Native Method)
[info] [sbt] 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
[info] [sbt] 	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
[info] [sbt] 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
[info] [sbt] 	at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:349)
[info] [sbt] 	at sbt.AbstractProcessBuilder.run(ProcessImpl.scala:128)
[info] [sbt] 	at sbt.AbstractProcessBuilder$$anonfun$runBuffered$1.apply(ProcessImpl.scala:159)
[info] [sbt] 	at sbt.AbstractProcessBuilder$$anonfun$runBuffered$1.apply(ProcessImpl.scala:159)
[info] [sbt] 	at sbt.compiler.javac.JavacLogger.buffer(JavacProcessLogger.scala:31)
[info] [sbt] 	at sbt.AbstractProcessBuilder.runBuffered(ProcessImpl.scala:159)
[info] [sbt] 	at sbt.AbstractProcessBuilder.$bang(ProcessImpl.scala:156)
[info] [sbt] 	at sbt.compiler.javac.ForkedJava$$anonfun$launch$1.apply(ForkedJava.scala:24)
[info] [sbt] 	at sbt.compiler.javac.ForkedJava$$anonfun$launch$1.apply(ForkedJava.scala:17)
[info] [sbt] 	at sbt.compiler.javac.ForkedJava$$anonfun$withArgumentFile$1.apply(ForkedJava.scala:47)
[info] [sbt] 	at sbt.compiler.javac.ForkedJava$$anonfun$withArgumentFile$1.apply(ForkedJava.scala:44)
[info] [sbt] 	at sbt.IO$.withTemporaryDirectory(IO.scala:291)
[info] [sbt] 	at sbt.compiler.javac.ForkedJava$.withArgumentFile(ForkedJava.scala:44)
[info] [sbt] 	at sbt.compiler.javac.ForkedJava$.launch(ForkedJava.scala:17)
[info] [sbt] 	at sbt.compiler.javac.ForkedJavaCompiler.run(ForkedJava.scala:68)
[info] [sbt] 	at sbt.compiler.javac.JavaCompilerAdapter.compileWithReporter(JavaCompilerAdapter.scala:31)
[info] [sbt] 	at sbt.compiler.javac.AnalyzingJavaCompiler$$anonfun$compile$1.apply$mcV$sp(AnalyzingJavaCompiler.scala:65)
[info] [sbt] 	at sbt.compiler.javac.AnalyzingJavaCompiler$$anonfun$compile$1.apply(AnalyzingJavaCompiler.scala:65)
[info] [sbt] 	at sbt.compiler.javac.AnalyzingJavaCompiler$$anonfun$compile$1.apply(AnalyzingJavaCompiler.scala:65)
[info] [sbt] 	at sbt.compiler.javac.AnalyzingJavaCompiler.timed(AnalyzingJavaCompiler.scala:93)
[info] [sbt] 	at sbt.compiler.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:64)
[info] [sbt] 	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileJava$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:61)
[info] [sbt] 	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileJava$1$1.apply(MixedAnalyzingCompiler.scala:61)
[info] [sbt] 	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileJava$1$1.apply(MixedAnalyzingCompiler.scala:61)
[info] [sbt] 	at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:75)
[info] [sbt] 	at sbt.compiler.MixedAnalyzingCompiler.compileJava$1(MixedAnalyzingCompiler.scala:60)
[info] [sbt] 	at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:65)
[info] [sbt] 	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
[info] [sbt] 	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
[info] [sbt] 	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
[info] [sbt] 	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
[info] [sbt] 	at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:31)
[info] [sbt] 	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:62)
[info] [sbt] 	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:61)
[info] [sbt] 	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:89)
[info] [sbt] 	at sbt.inc.Incremental$.compile(Incremental.scala:61)
[info] [sbt] 	at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
[info] [sbt] 	at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
[info] [sbt] 	at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
[info] [sbt] 	at sbt.Compiler$.compile(Compiler.scala:128)
[info] [sbt] 	at sbt.Compiler$.compile(Compiler.scala:114)
[info] [sbt] 	at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:814)
[info] [sbt] 	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:805)
[info] [sbt] 	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:803)
[info] [sbt] 	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[info] [sbt] 	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
[info] [sbt] 	at sbt.std.Transform$$anon$4.work(System.scala:63)
[info] [sbt] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
[info] [sbt] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
[info] [sbt] 	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[info] [sbt] 	at sbt.Execute.work(Execute.scala:235)
[info] [sbt] 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
[info] [sbt] 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
[info] [sbt] 	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[info] [sbt] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[info] [sbt] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] [sbt] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info] [sbt] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] [sbt] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info] [sbt] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info] [sbt] 	at java.lang.Thread.run(Thread.java:745)
[info] [sbt] [error] (search-index/compile:compileIncremental) java.io.IOException: Cannot run program "javac" (in directory "/home/datadesk/overview-server"): error=2, No such file or directory
[info] [sbt] [error] Total time: 2 s, completed Aug 7, 2015 2:12:44 PM
[error] ERROR - sbt exited with code 1. Please fix the error.
java.lang.RuntimeException: Nonzero exit code returned from runner: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last runner/compile:run for the full output.
[error] (runner/compile:run) Nonzero exit code returned from runner: 1
[error] Total time: 48 s, completed Aug 7, 2015 2:12:44 PM

**Comment by adamhooper** [comment]
Hi @borpglass,

Thanks for the bug report. I noticed our guide suggested installing `java-1.8.0-openjdk`. I've correct that: it should be `java-1.8.0-openjdk-devel`. Does everything work once you install `java-1.8.0-openjdk-devel`?

**Comment by borpglass** [comment]
Thanks! It looks like that at least squashed the specific error in question.

It also revealed a second set of errors. I'll open a separate issue for that one so we don't mix too much stuff together.

**Comment by borpglass** [comment]
Nevermind -- ran the auto/clean-fully.sh script (and also ran it with sudo for good measure) and then ran ./dev again. It now seems to be running a server, though it first spit out the non-fatal errors below. (Leaving this issue open for the moment in case these errors are more important than I think they are.)

[info] [overview-server] Running '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.51-4.b16.fc22.x86_64/jre/bin/java' '-Duser.timezone=UTC' '-Dpidfile.enabled=false' '-Dsbt.jse.engineType=Trireme' '-jar' '/home/datadesk/overview-server/runner/target/scala-2.11/classes/sbt-launch.jar' 'run'
[info] [redis] Running './deps/redis/dev.sh'
[info] [redis] cd src && make redis-server
[info] [redis] make[1]: Entering directory '/home/datadesk/overview-server/deps/redis/redis-2.8.17/src'
[info] [redis]     CC adlist.o
[info] [redis] /bin/sh: cc: command not found
[info] [redis] Makefile:197: recipe for target 'adlist.o' failed
[info] [redis] make[1]: *** [adlist.o] Error 127
[info] [redis] make[1]: Leaving directory '/home/datadesk/overview-server/deps/redis/redis-2.8.17/src'
[info] [redis] Makefile:6: recipe for target 'redis-server' failed
[info] [redis] make: *** [redis-server] Error 2
[error] ERROR - [redis] ./deps/redis/dev.sh: line 16: /home/datadesk/overview-server/deps/redis/redis-2.8.17/src/redis-server: No such file or directory
[info] Killing processes...
[info] [worker] Sending kill signal
[info] [message-broker] Sending kill signal
[info] [redis] Sending kill signal
[info] [search-index] Sending kill signal
[info] [overview-server] Sending kill signal
[info] [documentset-worker] Sending kill signal
[info] [database] pid=6241 xid=0 LOG:  00000: connection received: host=127.0.0.1 port=37208
[info] [database] pid=6241 xid=0 LOCATION:  BackendInitialize, postmaster.c:4003
[info] [database] pid=6241 xid=0 LOG:  00000: connection authorized: user=overview database=overview-dev
[info] [database] pid=6241 xid=0 LOCATION:  PerformAuthentication, postinit.c:258
[info] [database] pid=6245 xid=0 LOG:  00000: connection received: host=127.0.0.1 port=39124

<...server continues running...>

**Comment by borpglass** [comment]
Hmm ... looks like the place where everything goes off the rails is around here ...

[info] [redis] Running './deps/redis/dev.sh'
[info] [redis] cd src && make redis-server
[info] [redis] make[1]: Entering directory '/home/datadesk/overview-server/deps/redis/redis-2.8.17/src'
[info] [redis]     CC adlist.o
[info] [redis] /bin/sh: cc: command not found
[error] ERROR - [redis] ./deps/redis/dev.sh: line 16: /home/datadesk/overview-server/deps/redis/redis-2.8.17/src/redis-server: No such file or directory
[info] [redis] Makefile:197: recipe for target 'adlist.o' failed
[info] [redis] make[1]: *** [adlist.o] Error 127

... and since a "which cc" reveals that there's no command of that name, I tried this ...

sudo yum install gcc 

... and then ... 

export CC=gcc

... and then ...

cd /home/datadesk/overview-server/deps/redis/redis-2.8.17/deps

... and then ... 

make hiredis lua jemalloc linenoise

... and then re-ran ./dev    

... which dumped a bunch of additional output to the terminal and then appeared to start working. 

At least, going to localhost:9000 in a browser now displays pretty output. I haven't run the unit tests yet. 

Anyhow, the short version of this is that the documentation update was good, but that there may still be at least a few extra steps in Fedora 22:

-- Install gcc as documented above

-- Alias CC to gcc as documented above

-- Go and run the "make" command for a few extra dependencies as documented above. (It's possible that not all of these compilations are strictly necessary -- I got that list from a forum post.)

**Comment by adamhooper** [comment]
Thank you for putting the effort into this. And I'm glad you've gotten it working. I've changed the title of this issue and we'll keep it in mind.

When I have time, I'll verify your steps on my Fedora box and update the documentation.

**Comment by borpglass** [comment]
Sure thing! Thanks for the useful tools.

**Comment by xcolour** [comment]
I found my way here from #635. On a fresh Ubuntu 14.04, I just needed to install "build-essential", which is a meta-package for gcc and friends, and then re-run "./dev" to get Redis to build correctly. No need to build Redis by hand for me.

    $ sudo apt-get install build-essential
    $ ./dev

**Comment by adamhooper** [comment]
Life just got a little better: dev environments only require `docker` and `docker-compose`. See https://github.com/overview/overview-server/wiki/Setting-up-a-development-Environment for the new instructions.
