### ISSUE TITLE
Uploading .doc and .txt files

### ISSUE THREAD

**Issue by poinclin** [overview/overview-server#640]
Dear Overview team,

Discovered Overview server yesterday, and since this morning, I try to upload files. 
I managed to upload successfully PDF files, 
but several .doc, .docx and .txt files, from different sources, failed, even if it indicated as supported on Overview blog.

Thanks in advance,
Julien

**Comment by jstray** [comment]
Is this on overviewdocs.com, your own overview-local install, or dev
install? And failed how? Error messages?

**Comment by poinclin** [comment]
Sorry having not been precise enough:
- tested this morning between 9AM and 11AM French time
- it is on overviewdocs.com
- Firefox browser on Windows 7
- upload files is ok (button "Add files..."), PDF, DOC, DOCX and TXT
- click "Done adding files"
- very very long processing (more than 10 minutes for 5 files)
- when looking at "Your document sets" -> indication that "x documents could not be loaded" in the document set
- when looking into the specific document set, only PDF files are listed

NB: behaviour was reproducible several times this morning on different computers

Final result: upload was ok for all files, but processing was not for DOX, DOCX and TXT (not tested other filetypes)

Hope it helps,
Julien

**Comment by jstray** [comment]
Restarting the server seems to have fixed this. Not sure why it happened, but closing for now.
