### ISSUE TITLE
Integrate sourceAFRICA file import

### ISSUE THREAD

**Issue by DavidLemayian** [overview/overview-server#646]
[sourceAFRICA](https://sourceafrica.net) is growing with usage across the continent by media houses and we've recently received requests to integrate with Overview.

Fortunately sourceAFRICA is powered by DocumentCloud and would just need to extend the code. Would this be something you would consider? :)

Much love from Nairobi. 🇰🇪

**Comment by jstray** [comment]
HI! I'd love to support this. It depends on what you mean by "integrate." The simplest way would be to ru your own server then point it to your DocumentCloud install using the DOCUMENTCLOUD_URL configuration key.

Setting up your own Overview server:
https://github.com/overview/overview-local

More on configuration:
https://github.com/overview/overview-server/wiki/Configuration

**Comment by DavidLemayian** [comment]
@jstray Thanks for the quick response! That actually makes sense. I'll look at deploying our own Overview server.
