### ISSUE TITLE
Mixed content errors for plugins when serving via https

### ISSUE THREAD

**Issue by xcolour** [overview/overview-server#650]
I'm using `overview-local` to self-host Overview. I'm using Nginx as a proxy and to terminate https. Everything is running great, except plugin urls seem to be getting generated with the `http` rather than the `https` protocol. This causes mixed content errors in some browsers, so the requests get blocked. I'm setting `OVERVIEW_ADDRESS`, so otherwise I'm getting the right url for the plugins.

Am I missing a configuration setting to tell overview to generate https urls? I see that overviewdocs.org correctly generates https urls for plugins.

Thanks!

**Comment by jstray** [comment]
Good bug, I think I understand what's happening. You can change the plugin URLs to https in the Admin screen. Long term, the fix would be in https://github.com/overview/overview-docker/blob/master/plugin-setup/add-plugins.sh and a new docker images

**Comment by cljunggren** [comment]
I was able to use HAProxy (with some help from Jon on the initial setup) to bind the SSL cert to an external range 4000-4005 and then redirect to each internal port (3000, 30001, etc.) respectively. Then just go into the admin panel and change the plugins to use https://URL:port -- I'm sure you could do something similar with other proxy-type applications.

**Comment by adamhooper** [comment]
I run into this problem all the time when I try to use HTTPS plugins in dev mode. It seems to me the best long-term solution will be to make _everything_ HTTPS.

But that's Really Hard today.

A "localhost" self-signed certificate is very troublesome for end-users to accept: https://stackoverflow.com/questions/7580508/getting-chrome-to-accept-self-signed-localhost-certificate

Perhaps there's a way to make Docker fiddle with the host's DNS. It seems [possible](https://github.com/aacebedo/dnsdock). That way the URL could be "http://overview.local:9000".

Then again, how could we make this SSL cert legit, if we're actually providing users with the private key for download? Maybe a different approach is in order: scripting SSL-cert auto-generation in the client. Is that realistic? Letsencrypt, the only free provider I know of, [only works](https://certbot.eff.org/docs/using.html#standalone) on a publicly-visible server with DNS entries.

So, after all this ranting, I think the best solution today is: 1) auto-generating SSL cert on the client; and 2) helping the user accept that cert on the web browser/OS. That's Really Hard.

In sum: I think this bug will be here for a while. Maybe we should cross our fingers and hope that the Docker community takes a crack at it? We aren't the only ones with this problem: it's a big deal in web development, especially now that Chrome warns you when you aren't using HTTPS.

**Comment by adamhooper** [comment]
Oh actually, I misread this bug report! The bug is just that Overview is outputting the wrong URLs, only. It rewrites them every time you start it ... but I just gave the option to avoid that!

@xcolour Here you go:

1. Add `SKIP_PLUGIN_SETUP=true` to your `overview.env`.
1. Edit your plugin URLs at `https://[your Overview URL]/admin/plugins`. They won't be overwritten any more.
