### ISSUE TITLE
regex search in core

### ISSUE THREAD

**Issue by adamhooper** [overview/overview-server#676]
Our [overview-grep](https://github.com/overview/overview-grep) plugin is nice and all, but it'd be nicer to have it in core. In short:

Search parsing: `/search/` would do a grep. You're allowed a top-level grep, and you're allowed a top-level `AND` grep. The grep can occur on one field or on the default (`text+title`) field.

Execution: grep happens after search, before sort. It will only run on a configurable maximum -- `OV_GREP_MAXIMUM_N_DOCUMENTS`, default `500` or so? -- documents from the rest of the search. If the limit is exceeded, we add a warning.

Allow `NOT` on the regexes, too.

**Comment by adamhooper** [comment]
Tasks:

- [ ] `Query.normalize: Query` -- make `AndQuery` and `OrQuery` variable-length, and flatten trees like `AndQuery(AndQuery(AndQuery(...), ...), ...)` into a single `AndQuery`
- [ ] `DocumentSelectionBackend.queryToRegexes(query: Query): (List[(Field, re2j.Pattern)], List[SelectionWarning])` -- warning for all wrong regexes, warn for all regexes that aren't in a top-level `AndQuery`.
- [ ] `DocumentBackend.stream(documentSetId: Long, documentIds: Array[Long]): Stream[Document, akka.NotUsed]`
- [ ] Configure `OV_REGEX_SEARCH_MAX_N_DOCUMENTS` and make it accessible to `DocumentBackend.stream`
- [ ] `DocumentSelectionBackend.documentMatchesRegexes(document: Document, regexes: List[(Field, re2j.Pattern)]): Boolean`
- [ ] Add `DbDocumentSelectionBackend.filterIdsMatchingRegex(ids: Array[Long], request: SelectionRequest): (Array[Long], List[SelectionWarning])` -- which calls all the other methods
- [ ] Integration-test

**Comment by jstray** [comment]
Does the 500 limit mean I cannot use grep to count how many docs match a pattern? This has been the basis of several stories -- I'd rather wait a few minutes than just not be able to it at all.

**Comment by adamhooper** [comment]
That's a good point. I suggest we bring up that feature in the future -- so we'd be using this same code, but with a different scheduling strategy. (Maybe all it would take is a progressbar -- I'd need to think more about it. But certainly we can deliver _some_ value before we implement that.)
