### ISSUE TITLE
Document tab doesn't render PDF document in the view

### ISSUE THREAD

**Issue by adamhooper** [overview/overview-server#684]
Quoth @jayminkapish:

> We're spinning up OverviewDocs in our GKE cluster.
> 
> We're seeing a strange error every time we try to view a document in the PDF viewer(?) in the `overview-web` UI. I'm not very familiar with all the features of Overview yet so I could be doing something I'm not suppose to. 
> 
> From two views or tabs in the UI, Document and Text, Text does show parsed text from the PDF but clicking on Document tab logs the following and doesn't render document in the view:
> 
> ```
> WARN c.a.u.EC2MetadataUtils - Unable to retrieve the requested metadata.
> INFO application -   6ms GET /documents/115964116993.pdf -> 200
> ```
> 
> Since this error is recorded as Warn and response from /documents/115964116993.pdf is 200, there is no enough information in logs. Though, /documents/115964116993.txt does return parsed text from the document. That leads me to believe overview-web backend side of things wherever /documents/115964116993.pdf routes to, requires some AWS resource metadata, where resource could be an EC2 instance or something else, assuming we're operating in AWS? The only AWS dependency we have on our side is S3 and the IAM role + bucket policy doesn't allow any other resource access to the set keys than S3 bucket where documents are uploaded to.
> 
> Error leads me to the following file/line in aws-sdk-java repo:
> https://github.com/aws/aws-sdk-java/blob/4734de6fb0f80fe5768a6587aad3b9d0eaec388f/aws-java-sdk-core/src/main/java/com/amazonaws/util/EC2MetadataUtils.java#L386
> 
> I am still walking through the code from js/coffeescript to aws-sdk-java client and may update this issue with more findings.

**Comment by adamhooper** [comment]
Hi @jayminkapish,

Thanks for this. I haven't seen the error, but I think I can guess what's wrong.

The only thing we use `aws-sdk-java` for is "Blob Storage", which handles the storage and retrieval of files. We have two implementations: [FileStrategy](https://github.com/overview/overview-server/blob/master/common/src/main/scala/com/overviewdocs/blobstorage/FileStrategy.scala) and [S3Strategy](https://github.com/overview/overview-server/blob/master/common/src/main/scala/com/overviewdocs/blobstorage/S3Strategy.scala).

`overview-worker` writes documents to Blob Storage while there's a progress bar showing during document-set creation. `overview-web` reads documents from Blob Storage ... whenever.

I'm guessing that this error is coming because `overview-web` is configured to read from S3, but it's missing credentials. It seems plausible to me that S3 is noticing that it can't find the `AWS_ACCESS_KEY_ID` or `AWS_SECRET_ACCESS_KEY` environment variables, so it's assuming it's running within an iAM role and trying to grab credentials from its own metadata.

The bug here in Overview is that it's returning status code 200. That's clearly wrong. It should be giving a 500 error. I'll fix that.

Of course, a 500 error won't solve anything for _you_. `overview-web` can't read the files. You don't need a workaround: you need to fix the problem. There are three things you can do:

1. Give the `overview-web` pod read-only access to the S3 bucket(s) you use in `overview-worker`. I'm guessing you've solved this problem already on the worker side of things; I'm guessing you use credentials in environment variables. `overview-web` deserves a different role (read-only access), but same configuration approach.
2. Configure an NFS-ish approach that lets you mount the same directory on `overview-worker` (read-write) and `overview-web` (read-only).
3. Implement a `GCSStrategy`

**Comment by jayminkapish** [comment]
Thanks again Adam for quick reply.

I double confirmed that overview-web and overview-worker both have same AWS credentials. Bucket policy allows GetObject* for this user. I think that should be sufficient.

Scrolling through logs I am seeing following lines

```
WARN c.DocumentListController - Missing thumbnail data in blob storage for document 115964116994 at s3:overview-docs:57b426fd-dee6-49b3-883c-2278fcc2b9a2
WARN c.a.u.EC2MetadataUtils - Unable to retrieve the requested metadata.
WARN c.DocumentListController - Missing thumbnail data in blob storage for document 115964116993 at s3:overview-docs:c623b8b5-5279-4f4f-97ce-91d103df2de7
WARN c.a.u.EC2MetadataUtils - Unable to retrieve the requested metadata.
```

57b426fd-dee6-49b3-883c-2278fcc2b9a2 and c623b8b5-5279-4f4f-97ce-91d103df2de7 exist in the S3 bucket. What I am confused now at is logs say "Missing thumbnail data in blob storage". 

I have following secrets set in the deployment, can you take a look and confirm if values are correct or necessary?

```
  "blob-storage-file-base-directory": "s3:my-bucket",
  "blob-storage-file-contents-location": "s3:my-bucket",
  "blob-storage-file-view-location": "s3:my-bucket",
  "blob-storage-page-data-location": "s3:my-bucket",
```

I also see `net::ERR_SPDY_PROTOCOL_ERROR` in Chrome console that's very strange as protocol + host in the browser matches protocol + host in the request. My second guess is AJAX request isn't passing credentials with it? Which we is required since we've IAP enabled in kube ingress for this host.

**Comment by adamhooper** [comment]
Thumbnail data is a bit different. We use [GeneratePresignedUrlRequest](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/GeneratePresignedUrlRequest.html) to serve thumbnails from S3 itself. That might require extra permissions -- and maaaaybe even configuration on the S3 side?

These new messages have the same cause, though they're from a different part of the log. We generate presigned URLs (which givers you a `net::ERR_SPDY_PROTOCOL_ERROR`) when you open the _document list_; we download the PDF (which gives you an erroneous `200` response) when you open _a single document_.

I suggest, for now, you ignore the Thumbnail-related errors and focus on the PDF-related errors. (That lets us ignore GeneratePresignedUrlRequest, for now.)

We, too, use the same permissions for reading and writing. Here's our policy:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "OverviewProductionReadWriteFiles",
            "Effect": "Allow",
            "Action": [
                "s3:DeleteObject",
                "s3:GetObject",
                "s3:PutObject",
                "s3:GetBucketLocation",
                "s3:ListBucketMultipartUploads"
            ],
            "Resource": [
                "arn:aws:s3:::overview-production-file-contents/*",
                "arn:aws:s3:::overview-production-page-data/*",
                "arn:aws:s3:::overview-production-file-view/*"
            ]
        }
    ]
}
```

... I find it very strange that you're getting errors on the web side but not the worker side. They perform very similar operations.

I can't imagine how IAP would influence things. S3 requests are in their own thread pool: they know nothing about the HTTP requests that spawned them.

I think `Unable to retrieve the requested metadata` can only happen if the AWS SDK is looking up an iAM role; and it [would only do that](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html) if AWS _authentication_ (not authorization) using environment variables failed.

I suggest a triple-check: When you set `overview-web`'s environment variables in a shell (and clear out environment variables that _aren't_ set in `overview-web`'s config), `aws s3 cp s3://my-bucket/57b426fd-dee6-49b3-883c-2278fcc2b9a2 downloaded.bin` succeeds?

Please try whacking things for a while to convince yourself that A) these environment variables work; and B) these environment variables are correctly set and read by the `overview-web` process.

What I find so confusing is that this works on the worker but not on web. It's the same code, we Dockerize in the same manner ... there's so much similar that I'm having a hard time imagining what could be different, other than the environment.

**Comment by adamhooper** [comment]
Here's an ugly hack to make Overview display one particular environment variable. This may help test that your _method_ of passing environment variables is working. (It won't test that `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` are set.)

1. Log out of Overview
2. Set the environment variable `OV_WELCOME_BANNER` to `"Hellooooo from Adam!"`
3. Refresh the page.

The intro video should disappear and you should see `"Hellooooo from Adam!"` in its stead.

**Comment by jayminkapish** [comment]
You were right! This was related to AWS keys. One env var was missing: `AWS_REGION`, setting this everything is working. Oh I am super excited right now!

Thanks so much for your help Adam!

**Comment by adamhooper** [comment]
yay!

I'm going to reopen this issue and change its title. Overview should generate better error messages. The `200 OK` and the `net::ERR_SPDY_PROTOCOL_ERROR` you saw are crazy for such a common configuration error.
