### ISSUE TITLE
Fail to index a big file

### ISSUE THREAD

**Issue by sandrarosamadalena** [overview/overview-server#695]
Guys, I'm running Overview locally and I'm having trouble working with large files.
Uploading works normally. But it indexes only a portion of it, around 50%. As a result, searches do not work when I put a word that would be at the end of the document.
When I open the PDF through the interface, it comes complete. But when you access the raw text format view, you can see how far it has been indexed, about half.
I did not find any errors in the container's logs.

Congratulations on the project. I hope to contribute.

**Comment by sandrarosamadalena** [comment]
I just tested with the "Each page is one document" upload option. With this option, the entire file has been indexed.
What could be causing timeout in case of uploading as a document only?

**Comment by jstray** [comment]
There is a limit to the length of the internal text representation of a
document that Overview will index. You are probably running into that. How
long is the document?

  - Jonathan

**Comment by sandrarosamadalena** [comment]
The file is a PDF of 560mb and 2000 pages. It is great because there is a lot of mixed image in the body. But I'm not using OCR.
Do you know if this limit is changeable? I did not find this in the code.
If it is not something that can be edited, we could warn that it has been incomplete indexing to avoid problems for users who do not realize that the only part of the document is searchable.

**Comment by adamhooper** [comment]
Hi @sandrarosamadalena,

Our limit is 655360 characters per document. The limit prevents Overview from using an unreasonable amount of RAM when dealing with batches of documents.

It sounds like in your own deployment, you'd prefer to change your limit. I've exposed a new environment variable, `OV_MAX_CHARS_PER_DOCUMENT`. See our [configuration docs](https://github.com/overview/overview-server/wiki/Configuration) for more details.

640k characters doesn't sound like much, but it snowballs when dealing with Java Strings (2 to 4 bytes per character); batches (20 per batch when responding to API requests); network copies (multiply by 2); and concurrent requests on the web server (multiply by ~10 to be safe). 655360 characters per document can easily consume 1GB of RAM on the web server. If you double or triple the limit to support the documents you describe in this issue report, plan for Overview to require 2GB or 3GB when serving API requests.
