### ISSUE TITLE
User can load overviewdocs.com/documentsets but cannot load overviewdocs.com in incognito

### ISSUE THREAD

**Issue by jstray** [overview/overview-server#706]
Two of my team are currently reviewing a document set on overviewdocs.com. I get a timeout loading overviewdocs.com (landing page) on my machine. One of the current successful users cannot load overviewdocs.com in an incognito window on the same machine, the other can. 

One user reports could not load overviewdocs.com yesterday, worked a few minutes later.

blog.overviewdocs.com loads fine on all machines.

Server load balancing problem?  ¯\_(ツ)_/¯

**Comment by adamhooper** [comment]
This was a DNS error. It's been resolved.
